### ISSUE TITLE
output question

### ISSUE THREAD

**Issue by szgbjg** [StefOe/DPCR-AGB#3]
Hello, after I run the code (mseNet50), I get the loss curve and PT file, but I can't see the prediction results. What's the reason? I'm very sorry that I'm a beginner. Can you give me some guidance? Thank you very much!

**Comment by Fran-lose** [comment]
> 您好，在我运行代码 （mseNet50） 后，我得到了损失曲线和 PT 文件，但我看不到预测结果。原因是什么？我很抱歉我是初学者。您能给我一些指导吗？谢谢！
I would like to ask what your computer system is. If it is Windows, how did you download the MinkowskiEngine?

**Comment by szgbjg** [comment]
I'm not using Windows, I'm using Ubuntu

**Comment by Fran-lose** [comment]
> 我没有使用 Windows，我使用的是 Ubuntu

Thank you for your response. Was the entire process carried out using WSL?

**Comment by szgbjg** [comment]
Unfortunately, I failed and could not run this model on my own data, and now I am working on other experiments. I wish you success! My brother

**Comment by Fran-lose** [comment]
> 不幸的是，我失败了，无法在自己的数据上运行这个模型，现在我正在进行其他实验。祝您成功！我的兄弟

Were you able to successfully replicate the results of this paper?

**Comment by szgbjg** [comment]
> > Unfortunately, I failed and was unable to run this model on my own data and now I am working on other experiments. I wish you success! My brother
>
> Were you able to successfully replicate the results of this paper?
The results of this paper can be reproduced
